spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wizbrain_db
    username: postgres
    password: 1234
  flyway:
    baseline-on-migrate: true
api:
  text:
    model: text-davinci-003
    temperature: 0.7
    max-tokens: 2048
    top-p: 0.5
    frequency-penalty: 0
    presence-penalty: 0
  token: Bearer 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
  url:
    completions: https://api.openai.com/v1/completions
server:
  port: 8080